### PR TITLE
Fixed player not having control for a few seconds after skipping either of the Bomb Slot cutscenes in Sunchamber

### PR DESCRIPTION
**Pull request by MrMiguel211**

### CODE REVIEW

**Comment by toasterparty** [comment]
Can you clarify "nuance"? This goes in changelog because it's between versions

**Comment by Miepee** [comment]
https://discord.com/channels/914291389293027329/1245097053709795370

**Comment by MrMiguel211** [comment]
> Can you clarify "nuance"? This goes in changelog because it's between versions

This is not present in the last stable version of randovania

**Comment by Miepee** [comment]
This is randomprime, randomprime has its own changelog.

**Comment by MrMiguel211** [comment]
a

**Comment by toasterparty** [comment]
@Miepee I saw the thread but figured Miguel would name the PR the same thing as the bug report unless they found additional information when fixing

**Comment by MrMiguel211** [comment]
I changed the title btw

**Pull request merged**
