### PR TITLE
Fix reflected Charge/Beam Combo shots on randomized doors hurting the player.

### PR DESCRIPTION
**Pull request by MrMiguel211**

### CODE REVIEW

**Comment by Miepee** [comment]
I thought this was a feature.

**Comment by MrMiguel211** [comment]
I can't tell if you're being satirical or not

**Comment by Miepee** [comment]
I am not. I genuinely thought this was supposed to be a feature.

**Comment by MrMiguel211** [comment]
No, doors are not supposed to hurt the player.

**Comment by MrMiguel211** [comment]
No, doors are not supposed to hurt the player.

**Pull request closed without merging**
